name: the_drive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_native_splash: ^2.2.16
  video_player: ^2.4.10
  flutter_svg: ^1.1.6
  lottie: ^2.1.0
  intl_phone_field: ^3.1.0
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_staggered_grid_view: ^0.6.2
  rotated_corner_decoration: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_advanced_drawer: ^1.3.2
  badges: ^2.0.3
  pinput: ^2.2.19
  flutter_rating_bar: ^4.0.1
  swipe: ^0.0.1
  flutter_slidable: ^2.0.0
  qr_code_scanner: ^1.0.1
  flutter_wall_layout: ^2.1.1
  show_up_animation: ^2.0.0
  flutter_swiper_plus: ^2.0.4
  url_launcher: ^6.1.7
  flutter_bounce: ^1.1.0
  auto_route: ^5.0.4
  conditional_builder_null_safety: ^0.0.6
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  change_app_package_name: ^1.1.0
  fawry_sdk: ^0.1.9
  dio: ^4.0.6
  #ebraheem 
  connectivity: ^3.0.6
  get: ^4.6.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  image_picker: ^0.8.0+4
  flash: ^2.0.3+2
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^14.2.4
  phone_number: ^1.0.0
  jwt_decode: ^0.3.1
  shimmer: ^2.0.0
  permission_handler: ^8.2.2
  uuid: ^3.0.6
 


flutter_native_splash:
  color: "#000000"
  android_gravity: center
  image: assets/icons/app_logo.png
  android_12:
    image: assets/icons/app_logo.png
    android_gravity: center
    icon_background_color: "#000000"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.1.0+1

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - "assets/images/"
    - "assets/icons/"
    - "assets/videos/"
    - assets/language/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: main
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

    - family: arabic-main
      fonts:
        - asset: assets/fonts/alex-fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/alex-fonts/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/alex-fonts/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/alex-fonts/Alexandria-Medium.ttf
          weight: 500

    - family: arabic-main2
      fonts:
        - asset: assets/fonts/ibm-fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/ibm-fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm-fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm-fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500

    - family: arabic-main-cairo
      fonts:
        - asset: assets/fonts/cairoFonts/Cairo-Regular.ttf
        - asset: assets/fonts/cairoFonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairoFonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairoFonts/Cairo-Medium.ttf
          weight: 500


    - family: badge
      fonts:
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
